// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: grpc/RW.proto

package RW

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReadWriteClient is the client API for ReadWrite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReadWriteClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
}

type readWriteClient struct {
	cc grpc.ClientConnInterface
}

func NewReadWriteClient(cc grpc.ClientConnInterface) ReadWriteClient {
	return &readWriteClient{cc}
}

func (c *readWriteClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/RW.ReadWrite/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readWriteClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, "/RW.ReadWrite/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadWriteServer is the server API for ReadWrite service.
// All implementations must embed UnimplementedReadWriteServer
// for forward compatibility
type ReadWriteServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	mustEmbedUnimplementedReadWriteServer()
}

// UnimplementedReadWriteServer must be embedded to have forward compatible implementations.
type UnimplementedReadWriteServer struct {
}

func (UnimplementedReadWriteServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedReadWriteServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedReadWriteServer) mustEmbedUnimplementedReadWriteServer() {}

// UnsafeReadWriteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadWriteServer will
// result in compilation errors.
type UnsafeReadWriteServer interface {
	mustEmbedUnimplementedReadWriteServer()
}

func RegisterReadWriteServer(s grpc.ServiceRegistrar, srv ReadWriteServer) {
	s.RegisterService(&ReadWrite_ServiceDesc, srv)
}

func _ReadWrite_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadWriteServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RW.ReadWrite/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadWriteServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadWrite_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadWriteServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RW.ReadWrite/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadWriteServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadWrite_ServiceDesc is the grpc.ServiceDesc for ReadWrite service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadWrite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RW.ReadWrite",
	HandlerType: (*ReadWriteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _ReadWrite_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _ReadWrite_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/RW.proto",
}
